* лекц.
Я умру. Я сплю по 8 часов ежедневно. 
Нужно отсеивать не важное.

* Устройство.
     Стереотип мышления. Создание: уникальное, одновременное, связанное -
     удовольствие страдание.

* 
  Решить Сейчас измениться. Ответственный именно Я. 

* mind
Сонно, сопокойно.
сделать квест. сначала в комнате, надо выйти. найти ключ, замороженнй в
кастрюле воды в морозилке в холодильнике на цепях. 
* 9.12.2016.
      Проснулся, вставал тяжело. мысли бездельничать но стоит почитать бы.
      Сначала позавтракаю, чай шиповника с печеньками. Посмотрю туб, аниме.
      Но с этого не стоит начинать день, ведь с чего начнёшь так и пойдёт.
      Хотя сейчас я уже хоть немного начал писать (а надо читать и решать
      задачки), но скоро пойду бездельничать. 
      Ищу анимы(э) ещё качаю. Стоит сделать зарядку хотя бы, и музыку
      послушать - зарядиться. Посмотрел видео, аниме. Умылся обтиранием.
      Поставил стирку. Почитать бы. Почитал. Посмотрел своей гит, прибраться,
      увидел перевод markmanson, поискал. Помылся. Смотрел статьи. Варю обед,
      хотя рановато. Поел читая ГТ, смотря туб. чайтуб. хочется вернуться в
      пс1 рпг какую-нибудь. Почитал. зарядка. Покатался. голова начала
      болеть, съел 0.25 парацетамола. Почитал. Вспомни IF, копаю. brogue.
      идти в виконду? не пошёл, лежал час под одеялом, настроение на дно.
      Квест продумываю. Midi. Пил чай читая статью ГТ. Полежал. Постоял на
      руках. Поиграл в brogue. Постриг ногти. Поковырял квест. Нашёл
      эмуляторы старых терминалов. Лампово.
* 10.12.2016:
** Дела. 
      Проснулся, валялся, встал. Мысли более деловые, но попил чаю + туб +
      поел. Прочитал статью по питон. Программировал квест. Сделал зарядку.
      Очистили машину. Голова кружится. Готовлю обед. Пообедал+туб.
      Программирую, рисую шрифт. ГТ чай. Програм шрифт. туб. гость 73. vim.
      Ужин туб. тренировка. туб. тренировка. ГТ vim. Программировал.
      тренировался. ГТ vim. залип мыслю. Программировал. залип. Прибрался на
      гитхабе, добавил ридми. Потренировался. Туб ахреология. 
** Мысли
      Думаю стоит писать комменты на английском и подробнее на русском.
      Всё, пора худеть, буду много заниматься, стоя смотреть туб.
      Чаще писать мысли и избавляться от слов паразитов моих: так, итак, ну,
      дак, же... Дополнять список.
      g, и можно вернуться в открытом только что файле туда где был последний
      раз.
** Дела на потом
      Настроить русский в виме. Доизучить свёртку. Изучить регистры, буферы,
      команды в визуальном режиме.
      Сделать dotfiles dir и бэкап в неё и на гит.
* 11.12.2016
** Дела
Проснулся, посмотрел синий свет, встал, подышал свежим воздухом, сделал
зарядку. Сел записать. Надо бы начать утро с дела. Программировал.
Тренировался. Завтрак туб-архео, чай. Vim m. Программировал квест. Покатался,
потренировался. Поставил стираться. Почитал чистый код. Программировал.
Пробую пожарить картошку. Обед туб архэ. Читал про ppa. Программировал квест.
Читал чистый код. Туб бодибилдинг + тренировка.
** Мысли
Давно чувствую потребность углубить знания питона и методов
программирования-проектирования. Программируя чувствую свою небесполезность,
намного приятней так жить. Нужно разделять структуры данных и "объекты", то
есть структуру данных
с функциями работы с этими данными и отдельно функции логики работающие с этой
структурой данных. Значит отдельно модуль структуры данных и сервисными
функциями (или класс) и модуль логики работы с ней (или ещё класс?)
** Дела на потом
Прибраться в ~/bin и сделать бэкапинг, сделать их ссылками на хаб.
Начать делать скрипт автоматического развертывания среды, копирования
дотконфигов, скриптов в бин, создания папок...

* 12.12.2016
** Дела 
Проснулся, сделал зарядку. Почитал. Начал рефакторить, дальше делать
почему-то не хочется, а хочется улучшить. завтракал + туб, сериал. статьи.
Рефакторил. Помылся. Чай бутер туб. Статья ubuntu. Программировал квест.
Читал чистый код. тренировался чуток. Разбирался применять pytest. Дочитал
прог-фан. Программировал. Почитал прагматик. Тренировался. Не смог уснуть,
бессонница что ли.
** Мысли
Надо писать хоть по 1-2 тесту в день.
** На потом
vim mru, tagbar
vim :make надо использовать посмотреть как оно и если лучше то сделать
привязку

* 13.12.2016
** Дела
Проснулся, подышал. Зарядка. Чай... туб. Карта. Побегал в стену. Почитал
статью. Разобрал TODO в ТЗ. аниме чай. Программировал. Тренировался.
** Мысли
** На потом
* 1

** Дела
** Мысли
** На потом
