* лекц.
Я умру. Я сплю по 8 часов ежедневно. 
Нужно отсеивать не важное.

* Устройство.
     Стереотип мышления. Создание: уникальное, одновременное, связанное -
     удовольствие страдание.

* 
  Решить Сейчас измениться. Ответственный именно Я. 

* mind
Сонно, сопокойно.
сделать квест. сначала в комнате, надо выйти. найти ключ. 
* 9.12.2016.
      Проснулся, вставал тяжело. мысли бездельничать но стоит почитать бы.
      Сначала позавтракаю, чай шиповника с печеньками. Посмотрю туб, аниме.
      Но с этого не стоит начинать день, ведь с чего начнёшь так и пойдёт.
      Хотя сейчас я уже хоть немного начал писать (а надо читать и решать
      задачки), но скоро пойду бездельничать. 
      Ищу анимы(э) ещё качаю. Стоит сделать зарядку хотя бы, и музыку
      послушать - зарядиться. Посмотрел видео, аниме. Умылся обтиранием.
      Поставил стирку. Почитать бы. Почитал. Посмотрел своей гит, прибраться,
      увидел перевод markmanson, поискал. Помылся. Смотрел статьи. Варю обед,
      хотя рановато.
