* лекц.
Я умру. Я сплю по 8 часов ежедневно. 
Нужно отсеивать не важное.

* Устройство.
     Стереотип мышления. Создание: уникальное, одновременное, связанное -
     удовольствие страдание.

* 
  Решить Сейчас измениться. Ответственный именно Я. 

* mind
Сонно, сопокойно.
сделать квест. сначала в комнате, надо выйти. найти ключ, замороженнй в
кастрюле воды в морозилке в холодильнике на цепях. 
* 9.12.2016.
      Проснулся, вставал тяжело. мысли бездельничать но стоит почитать бы.
      Сначала позавтракаю, чай шиповника с печеньками. Посмотрю туб, аниме.
      Но с этого не стоит начинать день, ведь с чего начнёшь так и пойдёт.
      Хотя сейчас я уже хоть немного начал писать (а надо читать и решать
      задачки), но скоро пойду бездельничать. 
      Ищу анимы(э) ещё качаю. Стоит сделать зарядку хотя бы, и музыку
      послушать - зарядиться. Посмотрел видео, аниме. Умылся обтиранием.
      Поставил стирку. Почитать бы. Почитал. Посмотрел своей гит, прибраться,
      увидел перевод markmanson, поискал. Помылся. Смотрел статьи. Варю обед,
      хотя рановато. Поел читая ГТ, смотря туб. чайтуб. хочется вернуться в
      пс1 рпг какую-нибудь. Почитал. зарядка. Покатался. голова начала
      болеть, съел 0.25 парацетамола. Почитал. Вспомни IF, копаю. brogue.
      идти в виконду? не пошёл, лежал час под одеялом, настроение на дно.
      Квест продумываю. Midi. Пил чай читая статью ГТ. Полежал. Постоял на
      руках. Поиграл в brogue. Постриг ногти. Поковырял квест. Нашёл
      эмуляторы старых терминалов. Лампово.
* 10.12.2016:
      Проснулся, валялся, встал. Мысли более деловые, но попил чаю + туб +
      поел. Прочитал статью по питон.
