* мои
Используется ли какая то методология разработки
Как происходит workflow - постановка задачи, тестирование, тз, багтрек, интеграция, Ревью кода, контроль версий.
Чем мне конкретно придётся заниматься, что для этого нужно, настроить иметь.
По графику работы. как то фиксируются отработанные часы?
Дальнейшие интервью.
Есть ли документация.
* возможные
 1. Расскажите о себе. чёткая структура. образование, работа, проекты(либы, инструменты, языки, сложности)
 Проекты:
   
 2. Почему ушёл с работы. рост. неинтересная предметная область.
http://monitoring.lenreg.ru/?page_id=3634&LenRegOnce_paramPeriod=2015-01-01T00:00:00.000Z&STPL_0001_0005_CardParam=1&viewCode=STPL_0001_0004_dash
  3. что привлекает в данной должности. Желание принести пользу бизнесу и команде привнеся что-то уникальное.
 4. приемущества меня касающися данной должности. 
 5. недостатки.
  6. через 5(10) лет. Хотелось бы в ближайшие 2-3 года достаточно глубоко
 освоить python и связанные технологии, создавая полезный продукт. Лучше
 разобраться в устройстве Linux и операционных систем в целом. Освоить
 современный инструментарий, тесты, интеграцию, понимать построение
 архитектуры приложений.
 7. что читал. как учусь!. 

 последние: 
Программист фанатик
Ахо структуры данных и алгоритмы	
Простой Python	
Совершенный код	
Чистый код
Программист прагматик
Изучай Haskell во имя добра
введение в метаматематику
Теорема Абеля в задачах и решениях
Платон диалоги
  8. что делаю в свободное время. Катаюсь на роликах, читаю техническую,
  научно-популярную литературу, тренируюсь, медитирую, учусь разнообразным
  навыкам. играю в го. Изучаю linux и осваиваю разные утилиты. Читаю ИТ
  блоги. учусь рисовать и писать музыку. Философствую. Обдумываю пути
  улучшения проекта над которым работаю. Читаю английскую фентези. Решаю
  задачки (напр из проекта Эйлера)

* технич.
ООП
фреймворки.
Типы

с чего начать, что ставить. чем собирать, тестировать, куда заливать. стандарты кода.
Узнать кому сколько платят. И сказать сколько предложили мне :)

